name: Website

on:
    push:
        branches:
            - master
        paths: [ "frontend/**", ".github/workflows/website.yml"]
    pull_request:
        branches:
            - master
        paths: [ "frontend/**", ".github/workflows/website.yml"]

env:
    NODE_VERSION: "19"

jobs:
    # pnpm:
    #     name: install dependencies (pnpm)
    #     runs-on: ubuntu-latest
    hello:
        name: hello
        runs-on: ubuntu-latest
        steps: 
            - run: echo "hello"